# Architectural
initial_noise_size: 10
noise_size: 10
hidden_size: 96
mlp_size: 64
num_layers: 2

# Training hyperparams
generator_lr: 4.0e-5
discriminator_lr: 4.0e-5
batch_size: 1024
num_steps: 10000
init_mult1: 3
init_mult2: 0.5
weight_decay: 0.01
swa_step_start: 5000
dataset_size: 10000
t_size: 24 # Sample size
g_dt: 1.0
d_dt: 1.0

# Evaluation and plotting hyperparameters
steps_per_print: 10 # How often to print the loss.
num_plot_samples: 50 # How many samples to use on the plots at the end.
plot_locs: [0.1, 0.3, 0.5, 0.7, 0.9] # Plot some marginal distributions at this proportion of the way along.

# DBG
device: cuda
data_source: ou_proc
seed: 0
d_updates_per_g: 5
data_col: None
basic: false

# W&B
log_interval: 100
eval_interval: 500
samples_interval: 1000
save_interval: 2000
use_wandb: false
wandb_online: false
wandb_proj: 3infgan
wandb_name: default
config_num: 0
timestamp: None
