device: cuda
num_steps: 10000
batch_size: 1
init_mult1: 1
init_mult2: 1
generator_lr: 1
discriminator_lr: 1
weight_decay: 1

use_wandb: false
wandb_online: false
wandb_proj: hi
wandb_name: hi
config_name: hi
wandb_date_tag: 1
timestamp: None

num_features: 1
data_source: ou_proc
